### ISSUE TITLE
Solving n+1 problem

### ISSUE THREAD

**Issue by igo** [devoxa/prisma-relay-cursor-connection#201]
Is there a sample on how to deal with N+1 problem? Can library be used together with https://github.com/graphql/dataloader? If yes then how?

**Comment by queicherius** [comment]
You should be able to batch `findMany` queries together by following the [Prisma guide](https://www.prisma.io/docs/guides/prisma-guides/query-optimization-performance) for using `findUnique` instead. Prisma is also working on [doing that optimization automatically](https://github.com/prisma/prisma/issues/1477).

**Comment by igo** [comment]
Thanks for the feedback. Seems that it might work in a simple scenario. However I am not able to figure out how it can work in many-to-many relations with a `@relation` table. Considering this model where `User`s can be assigned to `Project`s:
```

model Diagram {
  id        Int      @id @default(autoincrement())
  name      String
  project   Project @relation(fields: [projectId], references: [id])
  projectId Int     @map(name: "project_id")
}

model Project {
  id        Int      @id @default(autoincrement())
  name      String
  diagrams Diagram[]
  UserProject UserProject[]
}

enum UserProjectRole {
  ADMIN
  WRITE
  READ
}

model UserProject {
  project   Project         @relation(fields: [projectId], references: [id])
  projectId Int             @map(name: "project_id")
  user      User            @relation(fields: [userId], references: [id])
  userId    Int             @map(name: "user_id")
  role      UserProjectRole @default(ADMIN)

  @@id([projectId, userId])
}

model User {
  id            Int       @id @default(autoincrement())
  name          String?
  userProjects UserProject[]
}
```

I thought it would be possible to do something like this in resolver but it doesn't work:

```js
User: {
  projects: async (parent, args, context, info) => {
    const result = await findManyCursorConnection(
      async (findManyArgs) => prisma.user.findUnique({
        ...findManyArgs,
        where: { id: parent.id },
      }).userProjects().project(),
      () => prisma.userProject.count({ where: { userId: parent.id } }),
      args
    )
    return result;
  }
},
```

Do you have any suggestions how can I make this work while solving N+1 problem?

**Comment by queicherius** [comment]
I think the `findManyArgs` has to go into the relation you are trying to turn into a connection:

```ts
async (findManyArgs) => prisma.user
  .findUnique({ where: { id: parent.id } })
  .userProjects()
  .project(findManyArgs)
```

---

Also, personally, when I have a N:M connection I would make this two connections to make it explicit. Something like this for your example:

```gql
{
  user {
    userProjects {
      edges {
        node {
          role
          project {
            id
          }
        }
      }
    }
  }
}
```

**Comment by igo** [comment]
Unfortunately that code throws an error:
```
TypeError: Cannot read property 'length' of undefined,
    at myapp/node_modules/@devoxa/prisma-relay-cursor-connection/dist/src/index.js:62:35,
    at Generator.next (<anonymous>),
    at fulfilled (myapp/node_modules/@devoxa/prisma-relay-cursor-connection/dist/src/index.js:15:58),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I can make it work only like this:

```js
async (findManyArgs) => (await prisma.userProject.findMany({
  ...findManyArgs,
  where: { userId: parent.id },
  include: { project: true }
})).map(up => up.project),
```

Regarding you suggestion, would it be possible to put the role on the edge?
```graphql
{
  user {
    userProjects {
      edges {
        role
        node {
          project {
            id
          }
        }
      }
    }
  }
}
```

**Comment by queicherius** [comment]
Oh yeah, it looks like Prisma does not support that syntax for N:M, where you chain multiple relations.

However, this works as expected. I didn't check if it batched the queries, but I'd assume so.

```ts
// Note <-> NoteTag <-> Tag
return findManyCursorConnection(
  (paginationArgs) => {
    return prisma.note
      .findUnique({ where: { id: noteId } })
      .noteTags(paginationArgs)
  },
  () => prisma.noteTag.count({ where: { noteId } }),
  connectionArgs
)
```

So this would work for my suggested GraphQL structure, tho I think it will be 2 queries if you read out both the `NoteTag` as well as the `Tag`. For your structure, I don't know what the best solution would be or if Prisma even supports that.

---

Closing this, because as shown above this package does support batched queries within the constraints that Prisma allows. Feel free to still comment.
