### ISSUE TITLE
Suggestion: order by cursor?

### ISSUE THREAD

**Issue by JaapWeijland** [devoxa/prisma-relay-cursor-connection#235]
Hi there,

I am new to cursor-based pagination, especially relay-style. However, as I understand, it is mandatory to order by the cursor to get predictable results, and this is by default not added to the sorting of the prisma query. Would it be an idea to add order by default, as I feel like it is assumable you want this when using this library?

**Comment by queicherius** [comment]
Hey!

It is not required to order by the cursor. Edges can be ordered however you want ([specification](https://relay.dev/graphql/connections.htm#sec-Edge-order)), with the only requirement of the order being consistent between requests.

So in code, you can add order like this, and it will work with Relay pagination/this package:

```ts
const result = await findManyCursorConnection(
  (args) => prisma.todo.findMany({ ...args, orderBy: { title: 'desc' } }),
  () => prisma.todo.count(),
  { last: 5, before: '5c11e0fa-fd6b-44ee-9016-0809ee2f2b9a' }
)
```
