### ISSUE TITLE
Read GraphQL fields and omit `totalCount` if it has not been requested

### ISSUE THREAD

**Issue by queicherius** [devoxa/prisma-relay-cursor-connection#291]
This was originally from https://github.com/devoxa/prisma-relay-cursor-connection/pull/102/files, which I closed for non-activity. If someone else would like that feature feel free to open a fresh PR.

**Comment by marinarierav** [comment]
Hi, I'm using your library and it would be great if we could add this feature. I have reopened a PR here:
https://github.com/devoxa/prisma-relay-cursor-connection/pull/393

**Comment by queicherius** [comment]
Thank you for the PR, I cleaned it up a little and added tests and documentation in #396 

Released as `2.1.0`, [documentation here](https://github.com/devoxa/prisma-relay-cursor-connection#resolve-information)).
