### ISSUE TITLE
Customize Connection

### ISSUE THREAD

**Issue by bosconian-dynamics** [devoxa/prisma-relay-cursor-connection#339]
Is there a way to customize the Connection object?

I would like to add a `pageCursors` property with cursors resolved to page numbers to assist in instances of traditional pagination, similar to the approach described in [this article](https://artsy.github.io/blog/2020/01/21/graphql-relay-windowed-pagination/).

...or at least play with it, anyway. I suspect a hybrid approach which could alternately use offsets instead of cursors when a page number is supplied would probably be the most efficient in the short term :)

**Comment by queicherius** [comment]
Right now there is no way to customize the connection in the way you are intending since this package is pretty tuned to the way that specifically the Relay connection is defined.

You should be able to fork it to play with it tho, the codebase is pretty small.

**Comment by bosconian-dynamics** [comment]
Fair fair - understood! I appreciate the insight :)
