### ISSUE TITLE
Prisma aggregate values are being stripped from the response

### ISSUE THREAD

**Issue by dani-z** [devoxa/prisma-relay-cursor-connection#352]
Hello 👋 

Thanks for this awesome lib, I was looking into implement this functionality by hand when I discovered it.
While playing with it I realised I was missing the `_count` and `_avg` from the response.

Here's the normal query which works fine:
```js
course.findMany({
    orderBy: {
      createdAt: "desc",
    },
    where,
    include: {
      _count: {
        select: {
          lesson: true,
        },
      },
    },
  });
```

Here's the query using the plugin:
```js
await findManyCursorConnection<
      Course,
      Pick<Prisma.CourseWhereUniqueInput, "eid">
    >(
      (args) => {
        return client.course.findMany({
          ...args,
          orderBy: {
            createdAt: "desc",
          },
          where,
          include: {
            _count: {
              select: {
                lesson: true,
              },
            },
          },
        });
      },
      () => client.course.count({ where }),
      { first, after },
      {
        getCursor: (record) => ({ eid: record.eid }),
        encodeCursor,
        decodeCursor,
      }
    );
```

![image](https://user-images.githubusercontent.com/394966/142599602-e15523cf-54ea-45e0-80b1-62446818d659.png)

Is this something you're looking to add in the future? I can also have a look into it when I get some time.

Thanks 🙏

**Comment by queicherius** [comment]
Hey there, glad you like the package!

This is already supported (and if you log the `node` you will see that is includes `_count`).

The reason it does not correctly infer the type is that you are manually overwriting it

```ts
await findManyCursorConnection<
  Course, // <-- here
  Pick<Prisma.CourseWhereUniqueInput, "eid">
>(
```

You can either provide the correct type yourself

```ts
await findManyCursorConnection<
  Course & { _count: { lessons: number } | null },
  Pick<Prisma.CourseWhereUniqueInput, "eid">
>(
```

or let TS infer it by pre-building the `findMany` call

```ts
const findMany = (args: Prisma.CourseFindManyArgs) =>
  client.course.findMany({
    ...args,
    // ...
    include: { _count: { select: { lessons: true } } },
  })

// If you're using TS <4.5 this utility type is be needed:
// type Awaited<T> = T extends PromiseLike<infer U> ? U : T

type CourseRecord = Awaited<ReturnType<typeof findMany>>[0]

const result = await findManyCursorConnection<CourseRecord, /* ... */>(
  // ...
)
```

Hope this helps!

**Comment by dani-z** [comment]
Ahh I completely ignored the good ol' console.log and went straight to TS, so foolish of me!
@queicherius it works like a charm, thanks so much for the quick reply. ❤️ 

Issue can be closed.
