### ISSUE TITLE
`nodes` field incompatible with custom edge

### ISSUE THREAD

**Issue by imkh** [devoxa/prisma-relay-cursor-connection#434]
The addition of the `nodes` field in #432 is a super useful change when working on the frontend side, but unfortunately it doesn't work great when using custom edges.

With custom edges, the `nodes` field contains an array of the `records` instead of an array of the `node` specified in `recordToEdge`:

```js
  {
    recordToEdge: (record) => ({
      node: record.foo,
      extraEdgeField: 'Bar',
    }),
  }
```

The typing of `nodes` is correct, but not the actual value inside. 

This use case is bit more complex so I wasn't able to find the change necessary to make things work 😕 

In the meantime, I use this workaround:
```js
const result = await findManyCursorConnection...

result.nodes = result.edges.map((edge) => edge.node);

return result;
```

---

Also, I notice that the `hasRequestedField` when requesting all records wasn't updated to check for `nodes`. Right now, it only checks for `edges` and `totalCount`.

https://github.com/devoxa/prisma-relay-cursor-connection/blob/7372ed82a7f96a5323dafb54b1fca895b3f139ba/src/index.ts#L78-L86

**Comment by queicherius** [comment]
Thank you! Fixed via https://github.com/devoxa/prisma-relay-cursor-connection/releases/tag/v2.2.1
