### ISSUE TITLE
Create pagination with prisma-relay-cursor-connection id is  number

### ISSUE THREAD

**Issue by BRAHAIM360** [devoxa/prisma-relay-cursor-connection#553]
I want to create pagination using prisma-relay-cursor-connection I'm using Postgresql with prisma in nestjs app
The id is number how we can handle pagination in this case  

```
 async GetPage() {
    return await findManyCursorConnection(
      args => this.Prisma.rue.findMany(args),
      () => this.Prisma.rue.count(),
      {},
     
    );
  }
```
TS Erorro :  
 Argument of type 'PrismaFindManyArguments<{ id: string; }>' is not assignable to parameter of type '{ select?: RueSelect; include?: RueInclude; where?: RueWhereInput; orderBy?: Enumerable<RueOrderByWithRelationInput>; cursor?: RueWhereUniqueInput; take?: number; skip?: number; distinct?: Enumerable<...>; }'.
  The types of 'cursor.id' are incompatible between these types.
    Type 'string' is not assignable to type 'number'.ts(2345)

**Comment by BRAHAIM360** [comment]
solve it by using `as any`
```
 async GetPage() {
    return await findManyCursorConnection(
      args => this.Prisma.rue.findMany(args as any),
      () => this.Prisma.rue.count(),
      {},
     
    );
  }
```

**Comment by queicherius** [comment]
You can also provide the cursor type as a generic: https://github.com/devoxa/prisma-relay-cursor-connection/blob/master/src/index.ts#L14
