### ISSUE TITLE
Handling Exception when Query Error in Callback Functions

### ISSUE THREAD

**Issue by sombochea** [devoxa/prisma-relay-cursor-connection#611]
**Hi, team**

I wonder about the function `findManyCursorConnection` that doesn't support handling outside the `try catch` block that I want to use with custom exception handling when the user passes any malformed query to the backend. Here is an example of my statement that not working with `try catch` below:

![image](https://user-images.githubusercontent.com/7059827/216746901-b1abda94-cb9a-48ab-be43-8e82066bd224.png)

Thank you!

**Comment by queicherius** [comment]
Hey, are you sure the error is throw inside of the `try` clause and not outside? We do something very similar and it works fine for us for malformed queries.
