### ISSUE TITLE
Support Entities With `id: Int`?

### ISSUE THREAD

**Issue by rjhilgefort** [devoxa/prisma-relay-cursor-connection#938]
Hello! Thanks for this package. I'm implementing it in a code base to transition from prisma1 -> prisma5. I ran into an issue where the types don't appear to be flowing and I'm unable to call `findManyCursorConnection`. It's a pretty simple call site but `findManyCursorConnection` doesn't appear to be inferring the correct types.

```
  findManyCursorConnection(
    args => prisma.creatorAnalytics.findMany(args),
    () => prisma.creatorAnalytics.count(),
    {},
  );
```

<img width="481" alt="image" src="https://github.com/user-attachments/assets/53ca9104-686b-4f82-a81a-7f4c8460cf10">

The error is: 
![CleanShot 2024-08-28 at 15 03 39@2x](https://github.com/user-attachments/assets/7d87fae8-f48a-4555-a4d8-42d6702bbf2b)

My schema looks like this. Is it because of the `id: Int` in my Prisma schema?
<img width="812" alt="image" src="https://github.com/user-attachments/assets/0e1b68f7-37fd-4609-8dfc-2566673e6efb">

**Comment by queicherius** [comment]
This supports number IDs (see [tests](https://github.com/devoxa/prisma-relay-cursor-connection/blob/master/tests/index.spec.ts#L111)). Your error talks about `compKey` which comes from your own codebase as far as I can tell.

**Comment by rjhilgefort** [comment]
It looks like it's not happy with the types flowing through to the `Cursor` generic

![CleanShot 2024-09-02 at 15 20 29@2x](https://github.com/user-attachments/assets/21c36719-4944-4963-8670-b98cbee05c5f)

**Comment by queicherius** [comment]
This is also supported ([see here](https://github.com/devoxa/prisma-relay-cursor-connection#type-safe-arguments)) and without more surrounding code it's impossible to debug your issue.

**Comment by rjhilgefort** [comment]
Appreciate the replies and understand it can be tough without a reproduction repo. That said, it seems to be a pretty simple problem with types not flowing when the `id` is `number` instead of `string`. When I mess with the type defs and change the generics assignment to be `{id: number}`, things work well for my problematic call site (but breaks all my other entities that are `{id: string}`).

<img width="465" alt="image" src="https://github.com/user-attachments/assets/d0695547-7cf7-4130-9c3e-819f6f463286">

In your previous comment, are you recommending that I use a custom cursor to coerce the number to be a string? Otherwise, my call site looks like the "type safe" example you linked. To be clear, types flow just fine as long as my entity has `{id: string}`.

**Comment by rjhilgefort** [comment]
I see this original issue and followed it through to the merged PR, but the code looks to have changed since the original issue.

https://github.com/devoxa/prisma-relay-cursor-connection/issues/1

I also noticed the tests and the apparent proof that it can work. When I tried it, my `includes` didn't flow through to the results and I couldn't access the related entities. 

https://github.com/devoxa/prisma-relay-cursor-connection/blob/master/tests/index.spec.ts#L173

**Comment by queicherius** [comment]
I just added a regression test for your use-case just to make sure it works.

It does, but you do have to manually pass the generic: https://github.com/devoxa/prisma-relay-cursor-connection/blob/master/tests/index.spec.ts#L194

```ts
//                                            v Your model type
const result = await findManyCursorConnection<User, { id: number }>(
//                                                    ^ Your cursor generic
```

I added a follow up-issue to make this easier: #944

**Comment by rjhilgefort** [comment]
Thanks again for the reply and additional tests, but I don't think this issue should be closed just yet. The problem remains that the results type of the `findMany` doesn't flow through out of the wrapper naturally. Providing the generics does "bandaid" the situation, but the types break down when you use `includes` or `select` in your `findMany` arguments.

Here you can see that `Category` exists on the results of the raw Prisma `findMany` call
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/50218af3-cdf2-476d-9132-319fa9b322ac">

Because of the manually provided generics, the `findMany` resulting types don't come out on the `edges`/`nodes` (if you don't provide generics for an `{id: string}` entity, the types flow fine).
<img width="703" alt="image" src="https://github.com/user-attachments/assets/02c3d10d-4297-4234-be4f-a86abfd8ec01">

Ideally, we would have the default assignment of the generics support both `{id: number}` and `{id: string}` without having to provide generics so the types can be inferred correctly. In the mean time, I've dupicated `findManyCursorConnection` to create an additional function that only handles `{id: number}`. Not ideal from a maintainability standpoint but it's the only thing I can figure so I can keep moving. Any further help would be greatly appreciated!

**Comment by queicherius** [comment]
> Providing the generics does "bandaid" the situation, but the types break down when you use `includes` or `select` in your `findMany` arguments.

Ah yeah. I added that to #944.

> Ideally, we would have the default assignment of the generics support both `{id: number}` and `{id: string}` without having to provide generics so the types can be inferred correctly.

I agree with this, I added a branch that adds some (failing) type tests for this case, but I could not figure out how to make this work. PRs welcome!

**Comment by rjhilgefort** [comment]
@queicherius Thanks! I couldn't figure out the types either in all my tinkering. If I figure it out, I'll contribute back here.
